matrix:
  include:
  - name: "xenial/flask/python3.7"
    language: python
    python: 3.7
    dist: xenial
    sudo: true
    env:
      - FLASK_ENV=development
      - API_VERSION=1
      - CONFIG_FILE=testing.json
      - TESTING=1
    before_script:
      - python3 -m pip install setuptools
      - python3 -m pip install -r requirements.txt
      - rm -Rf migrations
      - python3 $TRAVIS_BUILD_DIR/src/migrate.py db init
      - python3 $TRAVIS_BUILD_DIR/src/migrate.py db migrate
      - python3 $TRAVIS_BUILD_DIR/src/migrate.py db upgrade
    script:
      - python3 $TRAVIS_BUILD_DIR/src/test.py
