matrix:
  include:
    - php: 7.2
      env: TO_TEST=FRONTEND
      env: APP_ENV=testing
      env: APP_KEY=SomeRandomString
      env: DB_CONNECTION=mysql
      env: DB_HOST=127.0.0.1
      env: DB_PORT=3306
      env: DB_DATABASE=glucolog_test
      env: DB_USERNAME=root
      env: DB_PASSWORD=

    - python: 3.7
      env: FLASK_ENV=development
      env: API_VERSION=1
      env: CONFIG_FILE=testing.json
      env: TESTING=1

before_install:
  - mysql -e 'CREATE DATABASE glucolog_test;'

install:
  - cd ./src/python3/
  - pip install -r requirements.txt

before_script:
  - cd ./src/python3/
  - python migrate.py db init
  - python migrate.py db upgrade
  - python migrate.py db migrate
  - python migrate.py seed
  - cd ./src/php7/
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:install
  
script:
  - cd ./src/php7/
  - phpunit
  - cd ../../
  - cd ./src/python3/
  - python test.py

services:
  - mysql
