matrix:
  include:
  - name: "xenial/flask/python3.7"
    language: python
    python: 3.7
    dist: xenial
    sudo: false
    env:
      - FLASK_ENV=development
      - API_VERSION=1
      - CONFIG_FILE=testing.json
      - TESTING=1
    before_script:
      - python3 -m pip install -r requirements.txt
      - cd $TRAVIS_BUILD_DIR/src/
      - rm -Rf migrations
      - python3 migrate.py db init
      - python3 migrate.py db migrate
      - python3 migrate.py db upgrade
    script:
      - cd $TRAVIS_BUILD_DIR/src/
      - python3 test.py
